name: Deploy to AWS Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Set up Node.js using NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          source ~/.nvm/nvm.sh
          nvm install 20
          nvm use 20
          node -v
          npm -v 

      - name: Install dependencies
        run: |
          source ~/.nvm/nvm.sh
          npm install

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            source ~/.nvm/nvm.sh
            echo "Listing files in the home directory"
            ls -la /home/ubuntu
            echo "Listing files in the project directory"
            ls -la /home/ubuntu/projects
            echo "Listing files in the GoChapaa-backend directory"
            ls -la /home/ubuntu/projects/donor-project-backend
            cd /home/ubuntu/projects/donor-project-backend
            git pull origin main
            npm install
            npx sequelize-cli db:migrate
            npx sequelize-cli db:seed:all
            npm run build
            pm2 restart gochapaa-backend
